import json

basic_words = [
    # Verbs (동사)
    {"word": "be", "word_meaning": "~이다, 있다", "example_eng": "She is a teacher.", "example_kor": "그녀는 선생님이다."},
    {"word": "have", "word_meaning": "가지다", "example_eng": "I have a dog.", "example_kor": "나는 강아지를 가지고 있다."},
    {"word": "do", "word_meaning": "하다", "example_eng": "You can do it.", "example_kor": "너는 그것을 할 수 있다."},
    {"word": "say", "word_meaning": "말하다", "example_eng": "What did you say?", "example_kor": "무엇이라고 말했나요?"},
    {"word": "go", "word_meaning": "가다", "example_eng": "Let's go to the park.", "example_kor": "공원에 가자."},
    {"word": "get", "word_meaning": "얻다, 되다", "example_eng": "I need to get some sleep.", "example_kor": "나는 잠을 좀 자야 한다."},
    {"word": "make", "word_meaning": "만들다", "example_eng": "She made a cake for me.", "example_kor": "그녀는 나를 위해 케이크를 만들었다."},
    {"word": "know", "word_meaning": "알다", "example_eng": "I know his name.", "example_kor": "나는 그의 이름을 안다."},
    {"word": "think", "word_meaning": "생각하다", "example_eng": "I think it's a good idea.", "example_kor": "나는 그것이 좋은 생각이라고 생각한다."},
    {"word": "see", "word_meaning": "보다", "example_eng": "I see a bird in the tree.", "example_kor": "나무에 있는 새가 보인다."},
    {"word": "come", "word_meaning": "오다", "example_eng": "Please come to my house.", "example_kor": "우리 집에 와주세요."},
    {"word": "want", "word_meaning": "원하다", "example_eng": "I want to drink some water.", "example_kor": "나는 물을 좀 마시고 싶다."},
    {"word": "look", "word_meaning": "보다", "example_eng": "Look at the sky.", "example_kor": "하늘을 봐."},
    {"word": "use", "word_meaning": "사용하다", "example_eng": "Can I use your phone?", "example_kor": "네 전화기를 사용해도 될까?"},
    {"word": "find", "word_meaning": "찾다", "example_eng": "I can't find my keys.", "example_kor": "내 열쇠를 찾을 수가 없어."},
    {"word": "give", "word_meaning": "주다", "example_eng": "Please give me the book.", "example_kor": "그 책을 주세요."},
    {"word": "tell", "word_meaning": "말하다", "example_eng": "Can you tell me a story?", "example_kor": "이야기 하나 해줄 수 있니?"},
    {"word": "work", "word_meaning": "일하다", "example_eng": "My father works in an office.", "example_kor": "나의 아버지는 사무실에서 일하신다."},
    {"word": "call", "word_meaning": "부르다, 전화하다", "example_eng": "I will call you tonight.", "example_kor": "오늘 밤에 전화할게."},
    {"word": "try", "word_meaning": "시도하다", "example_eng": "You should try your best.", "example_kor": "너는 최선을 다해야 한다."},
    {"word": "ask", "word_meaning": "묻다", "example_eng": "He asked me a question.", "example_kor": "그는 나에게 질문을 했다."},
    {"word": "need", "word_meaning": "필요하다", "example_eng": "I need your help.", "example_kor": "나는 너의 도움이 필요하다."},
    {"word": "feel", "word_meaning": "느끼다", "example_eng": "I feel happy today.", "example_kor": "나는 오늘 행복함을 느낀다."},
    {"word": "become", "word_meaning": "~이 되다", "example_eng": "She wants to become a doctor.", "example_kor": "그녀는 의사가 되기를 원한다."},
    {"word": "leave", "word_meaning": "떠나다, 남기다", "example_eng": "The train leaves at 10 AM.", "example_kor": "기차는 오전 10시에 떠난다."},
    {"word": "put", "word_meaning": "놓다, 두다", "example_eng": "Put the book on the table.", "example_kor": "책상 위에 책을 놓아라."},
    {"word": "mean", "word_meaning": "의미하다", "example_eng": "What does this word mean?", "example_kor": "이 단어는 무슨 의미인가요?"},
    {"word": "keep", "word_meaning": "유지하다", "example_eng": "Please keep the door closed.", "example_kor": "문을 닫아두세요."},
    {"word": "let", "word_meaning": "허락하다", "example_eng": "Let me help you.", "example_kor": "제가 도와드릴게요."},
    {"word": "begin", "word_meaning": "시작하다", "example_eng": "Let's begin the class.", "example_kor": "수업을 시작합시다."},
    {"word": "seem", "word_meaning": "~처럼 보이다", "example_eng": "You seem tired.", "example_kor": "너 피곤해 보인다."},
    {"word": "help", "word_meaning": "돕다", "example_eng": "Can you help me with my homework?", "example_kor": "내 숙제 좀 도와줄 수 있니?"},
    {"word": "talk", "word_meaning": "이야기하다", "example_eng": "We talked for hours.", "example_kor": "우리는 몇 시간 동안 이야기했다."},
    {"word": "turn", "word_meaning": "돌다, 바꾸다", "example_eng": "Turn left at the corner.", "example_kor": "모퉁이에서 왼쪽으로 도세요."},
    {"word": "start", "word_meaning": "시작하다", "example_eng": "The game will start soon.", "example_kor": "경기가 곧 시작될 것이다."},
    {"word": "show", "word_meaning": "보여주다", "example_eng": "Show me your ticket, please.", "example_kor": "표를 보여주세요."},
    {"word": "hear", "word_meaning": "듣다", "example_eng": "I can't hear you.", "example_kor": "네 말이 안 들려."},
    {"word": "play", "word_meaning": "놀다, 연주하다", "example_eng": "Children love to play.", "example_kor": "아이들은 노는 것을 좋아한다."},
    {"word": "run", "word_meaning": "달리다", "example_eng": "He can run very fast.", "example_kor": "그는 매우 빨리 달릴 수 있다."},
    {"word": "move", "word_meaning": "움직이다", "example_eng": "Don't move!", "example_kor": "움직이지 마!"},
    {"word": "like", "word_meaning": "좋아하다", "example_eng": "I like apples.", "example_kor": "나는 사과를 좋아한다."},
    {"word": "live", "word_meaning": "살다", "example_eng": "I live in Seoul.", "example_kor": "나는 서울에 산다."},
    {"word": "believe", "word_meaning": "믿다", "example_eng": "I believe in you.", "example_kor": "나는 너를 믿는다."},
    {"word": "hold", "word_meaning": "잡다", "example_eng": "Please hold my hand.", "example_kor": "제 손을 잡아주세요."},
    {"word": "bring", "word_meaning": "가져오다", "example_eng": "Bring me a glass of water.", "example_kor": "물 한 잔 가져다주세요."},
    {"word": "happen", "word_meaning": "일어나다", "example_eng": "What happened?", "example_kor": "무슨 일이야?"},
    {"word": "write", "word_meaning": "쓰다", "example_eng": "Write your name here.", "example_kor": "여기에 이름을 쓰세요."},
    {"word": "sit", "word_meaning": "앉다", "example_eng": "Please sit down.", "example_kor": "앉으세요."},
    {"word": "stand", "word_meaning": "서다", "example_eng": "Stand up, please.", "example_kor": "일어서세요."},
    {"word": "lose", "word_meaning": "잃다", "example_eng": "Don't lose your passport.", "example_kor": "여권을 잃어버리지 마세요."},
    {"word": "pay", "word_meaning": "지불하다", "example_eng": "I'll pay for dinner.", "example_kor": "저녁은 제가 살게요."},
    {"word": "meet", "word_meaning": "만나다", "example_eng": "Nice to meet you.", "example_kor": "만나서 반갑습니다."},
    {"word": "include", "word_meaning": "포함하다", "example_eng": "The price includes tax.", "example_kor": "그 가격은 세금을 포함합니다."},
    {"word": "continue", "word_meaning": "계속하다", "example_eng": "Please continue your story.", "example_kor": "이야기를 계속해주세요."},
    {"word": "set", "word_meaning": "설정하다, 놓다", "example_eng": "He set a new record.", "example_kor": "그는 새로운 기록을 세웠다."},
    {"word": "learn", "word_meaning": "배우다", "example_eng": "I want to learn English.", "example_kor": "나는 영어를 배우고 싶다."},
    {"word": "change", "word_meaning": "바꾸다", "example_eng": "People can change.", "example_kor": "사람은 변할 수 있다."},
    {"word": "lead", "word_meaning": "이끌다", "example_eng": "She will lead the team.", "example_kor": "그녀가 팀을 이끌 것이다."},
    {"word": "understand", "word_meaning": "이해하다", "example_eng": "I don't understand the question.", "example_kor": "질문을 이해하지 못하겠습니다."},
    {"word": "watch", "word_meaning": "보다", "example_eng": "Let's watch a movie.", "example_kor": "영화 보자."},
    {"word": "follow", "word_meaning": "따라가다", "example_eng": "Follow me, please.", "example_kor": "저를 따라오세요."},
    {"word": "stop", "word_meaning": "멈추다", "example_eng": "The bus stopped suddenly.", "example_kor": "버스가 갑자기 멈췄다."},
    {"word": "create", "word_meaning": "창조하다", "example_eng": "He created a masterpiece.", "example_kor": "그는 걸작을 창조했다."},
    {"word": "speak", "word_meaning": "말하다", "example_eng": "He speaks three languages.", "example_kor": "그는 3개 국어를 한다."},
    {"word": "read", "word_meaning": "읽다", "example_eng": "I like to read books.", "example_kor": "나는 책 읽는 것을 좋아한다."},
    {"word": "allow", "word_meaning": "허락하다", "example_eng": "Smoking is not allowed here.", "example_kor": "이곳에서는 흡연이 허용되지 않습니다."},
    {"word": "add", "word_meaning": "더하다", "example_eng": "Add some sugar to your tea.", "example_kor": "차에 설탕을 좀 넣으세요."},
    {"word": "spend", "word_meaning": "쓰다, 보내다", "example_eng": "How do you spend your free time?", "example_kor": "여가 시간을 어떻게 보내세요?"},
    {"word": "grow", "word_meaning": "자라다", "example_eng": "Plants need water to grow.", "example_kor": "식물은 자라기 위해 물이 필요하다."},
    {"word": "open", "word_meaning": "열다", "example_eng": "Please open the window.", "example_kor": "창문을 열어주세요."},
    {"word": "walk", "word_meaning": "걷다", "example_eng": "I walk to work every day.", "example_kor": "나는 매일 걸어서 출근한다."},
    {"word": "win", "word_meaning": "이기다", "example_eng": "I hope our team will win.", "example_kor": "우리 팀이 이기기를 바란다."},
    {"word": "offer", "word_meaning": "제공하다", "example_eng": "They offered me a job.", "example_kor": "그들은 나에게 일자리를 제안했다."},
    {"word": "remember", "word_meaning": "기억하다", "example_eng": "I remember his face.", "example_kor": "나는 그의 얼굴을 기억한다."},
    {"word": "love", "word_meaning": "사랑하다", "example_eng": "I love my family.", "example_kor": "나는 나의 가족을 사랑한다."},
    {"word": "consider", "word_meaning": "고려하다", "example_eng": "You should consider his feelings.", "example_kor": "너는 그의 감정을 고려해야 한다."},
    {"word": "appear", "word_meaning": "나타나다", "example_eng": "A ship appeared on the horizon.", "example_kor": "수평선 위로 배 한 척이 나타났다."},
    {"word": "buy", "word_meaning": "사다", "example_eng": "I need to buy some groceries.", "example_kor": "나는 식료품을 좀 사야 한다."},
    {"word": "wait", "word_meaning": "기다리다", "example_eng": "Wait for me!", "example_kor": "나를 기다려!"},
    {"word": "die", "word_meaning": "죽다", "example_eng": "All living things eventually die.", "example_kor": "모든 생명체는 결국 죽는다."},
    {"word": "send", "word_meaning": "보내다", "example_eng": "I will send you an email.", "example_kor": "이메일을 보내드릴게요."},
    {"word": "expect", "word_meaning": "기대하다", "example_eng": "I expect you to be on time.", "example_kor": "나는 네가 제시간에 오기를 기대한다."},
    {"word": "build", "word_meaning": "짓다", "example_eng": "They are building a new bridge.", "example_kor": "그들은 새로운 다리를 짓고 있다."},
    {"word": "stay", "word_meaning": "머무르다", "example_eng": "I will stay at a hotel.", "example_kor": "나는 호텔에 머무를 것이다."},
    {"word": "fall", "word_meaning": "떨어지다", "example_eng": "Leaves fall from the trees in autumn.", "example_kor": "가을에는 나뭇잎이 떨어진다."},
    {"word": "cut", "word_meaning": "자르다", "example_eng": "Be careful when you cut the paper.", "example_kor": "종이를 자를 때 조심하세요."},
    {"word": "reach", "word_meaning": "도달하다", "example_eng": "We will reach the summit tomorrow.", "example_kor": "우리는 내일 정상에 도달할 것이다."},
    {"word": "kill", "word_meaning": "죽이다", "example_eng": "He killed the insect with a spray.", "example_kor": "그는 스프레이로 그 벌레를 죽였다."},
    {"word": "raise", "word_meaning": "올리다, 기르다", "example_eng": "Please raise your hand.", "example_kor": "손을 들어주세요."},
    # Nouns (명사)
    {"word": "time", "word_meaning": "시간", "example_eng": "What time is it?", "example_kor": "지금 몇 시인가요?"},
    {"word": "person", "word_meaning": "사람", "example_eng": "He is a kind person.", "example_kor": "그는 친절한 사람이다."},
    {"word": "year", "word_meaning": "년, 해", "example_eng": "I will graduate next year.", "example_kor": "나는 내년에 졸업할 것이다."},
    {"word": "way", "word_meaning": "방법, 길", "example_eng": "Is this the right way?", "example_kor": "이 길이 맞나요?"},
    {"word": "day", "word_meaning": "날, 하루", "example_eng": "Today is a beautiful day.", "example_kor": "오늘은 아름다운 날이다."},
    {"word": "thing", "word_meaning": "것, 물건", "example_eng": "What is that thing?", "example_kor": "저것은 무엇인가요?"},
    {"word": "man", "word_meaning": "남자", "example_eng": "A man is walking down the street.", "example_kor": "한 남자가 길을 걷고 있다."},
    {"word": "world", "word_meaning": "세계", "example_eng": "We live in a beautiful world.", "example_kor": "우리는 아름다운 세상에 살고 있다."},
    {"word": "life", "word_meaning": "삶, 인생", "example_eng": "Life is short.", "example_kor": "인생은 짧다."},
    {"word": "hand", "word_meaning": "손", "example_eng": "She has small hands.", "example_kor": "그녀는 손이 작다."},
    {"word": "part", "word_meaning": "부분", "example_eng": "This is the best part of the movie.", "example_kor": "이것이 영화의 최고의 부분이다."},
    {"word": "child", "word_meaning": "아이", "example_eng": "The child is playing with a toy.", "example_kor": "아이가 장난감을 가지고 놀고 있다."},
    {"word": "eye", "word_meaning": "눈", "example_eng": "She has blue eyes.", "example_kor": "그녀는 파란 눈을 가졌다."},
    {"word": "woman", "word_meaning": "여자", "example_eng": "That woman is my mother.", "example_kor": "저 여자는 나의 어머니다."},
    {"word": "place", "word_meaning": "장소", "example_eng": "This is a quiet place.", "example_kor": "이곳은 조용한 장소다."},
    {"word": "week", "word_meaning": "주", "example_eng": "There are seven days in a week.", "example_kor": "일주일은 7일이다."},
    {"word": "case", "word_meaning": "사건, 경우", "example_eng": "The police are investigating the case.", "example_kor": "경찰이 그 사건을 조사하고 있다."},
    {"word": "point", "word_meaning": "점, 요점", "example_eng": "What is your point?", "example_kor": "당신의 요점은 무엇입니까?"},
    {"word": "government", "word_meaning": "정부", "example_eng": "The government made a new law.", "example_kor": "정부는 새로운 법을 만들었다."},
    {"word": "company", "word_meaning": "회사", "example_eng": "He works for a big company.", "example_kor": "그는 큰 회사에서 일한다."},
    {"word": "number", "word_meaning": "숫자, 번호", "example_eng": "My favorite number is seven.", "example_kor": "내가 가장 좋아하는 숫자는 7이다."},
    {"word": "group", "word_meaning": "그룹, 집단", "example_eng": "A group of students entered the room.", "example_kor": "한 그룹의 학생들이 방으로 들어왔다."},
    {"word": "problem", "word_meaning": "문제", "example_eng": "I have a problem with my car.", "example_kor": "내 차에 문제가 있다."},
    {"word": "fact", "word_meaning": "사실", "example_eng": "It is a well-known fact.", "example_kor": "그것은 잘 알려진 사실이다."},
    {"word": "school", "word_meaning": "학교", "example_eng": "My sister goes to elementary school.", "example_kor": "내 여동생은 초등학교에 다닌다."},
    {"word": "student", "word_meaning": "학생", "example_eng": "I am a college student.", "example_kor": "나는 대학생이다."},
    {"word": "country", "word_meaning": "나라", "example_eng": "Korea is my country.", "example_kor": "한국은 나의 나라이다."},
    {"word": "home", "word_meaning": "집", "example_eng": "I want to go home.", "example_kor": "나는 집에 가고 싶다."},
    {"word": "water", "word_meaning": "물", "example_eng": "I am thirsty. I need some water.", "example_kor": "목이 마르다. 물이 좀 필요하다."},
    {"word": "room", "word_meaning": "방", "example_eng": "This is my room.", "example_kor": "여기는 내 방이다."},
    {"word": "mother", "word_meaning": "어머니", "example_eng": "My mother is a nurse.", "example_kor": "나의 어머니는 간호사이다."},
    {"word": "area", "word_meaning": "지역", "example_eng": "This area is famous for its beaches.", "example_kor": "이 지역은 해변으로 유명하다."},
    {"word": "money", "word_meaning": "돈", "example_eng": "I don't have enough money.", "example_kor": "나는 돈이 충분하지 않다."},
    {"word": "story", "word_meaning": "이야기", "example_eng": "He told me an interesting story.", "example_kor": "그는 나에게 재미있는 이야기를 해주었다."},
    {"word": "month", "word_meaning": "달", "example_eng": "January is the first month of the year.", "example_kor": "1월은 한 해의 첫 번째 달이다."},
    {"word": "book", "word_meaning": "책", "example_eng": "I am reading a book.", "example_kor": "나는 책을 읽고 있다."},
    {"word": "job", "word_meaning": "직업", "example_eng": "He is looking for a new job.", "example_kor": "그는 새로운 직업을 찾고 있다."},
    {"word": "word", "word_meaning": "단어", "example_eng": "This word is difficult to pronounce.", "example_kor": "이 단어는 발음하기 어렵다."},
    {"word": "business", "word_meaning": "사업", "example_eng": "He runs his own business.", "example_kor": "그는 자신의 사업을 운영한다."},
    {"word": "side", "word_meaning": "쪽, 편", "example_eng": "Which side are you on?", "example_kor": "너는 어느 편이니?"},
    {"word": "kind", "word_meaning": "종류", "example_eng": "What kind of music do you like?", "example_kor": "어떤 종류의 음악을 좋아하세요?"},
    {"word": "head", "word_meaning": "머리", "example_eng": "My head hurts.", "example_kor": "머리가 아프다."},
    {"word": "house", "word_meaning": "집", "example_eng": "They live in a big house.", "example_kor": "그들은 큰 집에 산다."},
    {"word": "friend", "word_meaning": "친구", "example_eng": "He is my best friend.", "example_kor": "그는 나의 가장 친한 친구다."},
    {"word": "father", "word_meaning": "아버지", "example_eng": "My father is a doctor.", "example_kor": "나의 아버지는 의사이다."},
    {"word": "power", "word_meaning": "힘, 권력", "example_eng": "Knowledge is power.", "example_kor": "아는 것이 힘이다."},
    {"word": "hour", "word_meaning": "시간", "example_eng": "I will be back in an hour.", "example_kor": "한 시간 후에 돌아올게."},
    {"word": "game", "word_meaning": "게임, 경기", "example_eng": "Let's play a game.", "example_kor": "게임하자."},
    {"word": "line", "word_meaning": "선, 줄", "example_eng": "Please stand in line.", "example_kor": "줄을 서세요."},
    {"word": "end", "word_meaning": "끝", "example_eng": "This is the end of the road.", "example_kor": "이것이 길의 끝이다."},
    {"word": "car", "word_meaning": "자동차", "example_eng": "I drive a blue car.", "example_kor": "나는 파란색 차를 운전한다."},
    {"word": "city", "word_meaning": "도시", "example_eng": "Paris is a beautiful city.", "example_kor": "파리는 아름다운 도시이다."},
    # Adjectives (형용사)
    {"word": "good", "word_meaning": "좋은", "example_eng": "This is a good book.", "example_kor": "이것은 좋은 책이다."},
    {"word": "new", "word_meaning": "새로운", "example_eng": "I bought a new car.", "example_kor": "나는 새 차를 샀다."},
    {"word": "first", "word_meaning": "첫 번째의", "example_eng": "This is my first time here.", "example_kor": "여기 온 것은 이번이 처음이다."},
    {"word": "last", "word_meaning": "마지막의", "example_eng": "It's the last day of the year.", "example_kor": "올해의 마지막 날이다."},
    {"word": "long", "word_meaning": "긴", "example_eng": "It was a long journey.", "example_kor": "그것은 긴 여정이었다."},
    {"word": "great", "word_meaning": "위대한, 훌륭한", "example_eng": "He was a great leader.", "example_kor": "그는 위대한 지도자였다."},
    {"word": "little", "word_meaning": "작은", "example_eng": "She lives in a little house.", "example_kor": "그녀는 작은 집에 산다."},
    {"word": "other", "word_meaning": "다른", "example_eng": "Do you have any other questions?", "example_kor": "다른 질문 있나요?"},
    {"word": "old", "word_meaning": "오래된, 늙은", "example_eng": "My grandfather is very old.", "example_kor": "나의 할아버지는 매우 늙으셨다."},
    {"word": "right", "word_meaning": "오른쪽의, 옳은", "example_eng": "That's the right answer.", "example_kor": "그것이 정답이다."},
    {"word": "big", "word_meaning": "큰", "example_eng": "An elephant is a big animal.", "example_kor": "코끼리는 큰 동물이다."},
    {"word": "high", "word_meaning": "높은", "example_eng": "The mountain is very high.", "example_kor": "그 산은 매우 높다."},
    {"word": "different", "word_meaning": "다른", "example_eng": "We have different opinions.", "example_kor": "우리는 다른 의견을 가지고 있다."},
    {"word": "small", "word_meaning": "작은", "example_eng": "An ant is a small insect.", "example_kor": "개미는 작은 곤충이다."},
    {"word": "large", "word_meaning": "큰", "example_eng": "We need a large table.", "example_kor": "우리는 큰 테이블이 필요하다."},
    {"word": "next", "word_meaning": "다음의", "example_eng": "See you next week.", "example_kor": "다음 주에 봐요."},
    {"word": "early", "word_meaning": "이른", "example_eng": "I woke up early this morning.", "example_kor": "나는 오늘 아침 일찍 일어났다."},
    {"word": "young", "word_meaning": "어린, 젊은", "example_eng": "He is too young to drive.", "example_kor": "그는 운전하기에는 너무 어리다."},
    {"word": "important", "word_meaning": "중요한", "example_eng": "This is an important meeting.", "example_kor": "이것은 중요한 회의이다."},
    {"word": "few", "word_meaning": "소수의", "example_eng": "I have a few friends.", "example_kor": "나는 친구가 몇 명 있다."},
    {"word": "public", "word_meaning": "공공의", "example_eng": "This is a public library.", "example_kor": "이곳은 공공 도서관이다."},
    {"word": "bad", "word_meaning": "나쁜", "example_eng": "That was a bad movie.", "example_kor": "그것은 나쁜 영화였다."},
    {"word": "same", "word_meaning": "같은", "example_eng": "We are the same age.", "example_kor": "우리는 동갑이다."},
    {"word": "able", "word_meaning": "~할 수 있는", "example_eng": "You are able to do anything.", "example_kor": "너는 무엇이든 할 수 있다."},
    {"word": "beautiful", "word_meaning": "아름다운", "example_eng": "She is a beautiful woman.", "example_kor": "그녀는 아름다운 여성이다."},
    {"word": "happy", "word_meaning": "행복한", "example_eng": "I'm so happy to see you.", "example_kor": "너를 보니 정말 행복해."},
    {"word": "easy", "word_meaning": "쉬운", "example_eng": "The test was very easy.", "example_kor": "시험은 매우 쉬웠다."},
    {"word": "difficult", "word_meaning": "어려운", "example_eng": "This math problem is difficult.", "example_kor": "이 수학 문제는 어렵다."},
    {"word": "strong", "word_meaning": "강한", "example_eng": "He has a strong body.", "example_kor": "그는 강한 몸을 가지고 있다."},
    {"word": "cold", "word_meaning": "추운, 차가운", "example_eng": "It's cold outside.", "example_kor": "밖은 춥다."},
    # Adverbs (부사)
    {"word": "always", "word_meaning": "항상", "example_eng": "I always drink coffee in the morning.", "example_kor": "나는 아침에 항상 커피를 마신다."},
    {"word": "never", "word_meaning": "결코 ~않다", "example_eng": "I will never forget you.", "example_kor": "나는 결코 너를 잊지 않을 것이다."},
    {"word": "often", "word_meaning": "자주", "example_eng": "I often go to the movies.", "example_kor": "나는 영화를 보러 자주 간다."},
    {"word": "sometimes", "word_meaning": "때때로", "example_eng": "Sometimes I feel lonely.", "example_kor": "나는 때때로 외로움을 느낀다."},
    {"word": "here", "word_meaning": "여기에", "example_eng": "Please come here.", "example_kor": "이리 오세요."},
    {"word": "there", "word_meaning": "거기에", "example_eng": "My bag is over there.", "example_kor": "내 가방은 저기에 있다."},
    {"word": "now", "word_meaning": "지금", "example_eng": "I have to go now.", "example_kor": "나는 지금 가야 한다."},
    {"word": "then", "word_meaning": "그때", "example_eng": "I was very young then.", "example_kor": "나는 그때 매우 어렸다."},
    {"word": "really", "word_meaning": "정말로", "example_eng": "I'm really sorry.", "example_kor": "정말로 미안해."},
    {"word": "very", "word_meaning": "매우", "example_eng": "She is very smart.", "example_kor": "그녀는 매우 똑똑하다."},
    # Prepositions (전치사)
    {"word": "to", "word_meaning": "~로", "example_eng": "I'm going to the store.", "example_kor": "나는 가게에 가고 있다."},
    {"word": "of", "word_meaning": "~의", "example_eng": "This is a picture of my family.", "example_kor": "이것은 나의 가족 사진이다."},
    {"word": "in", "word_meaning": "~안에", "example_eng": "The cat is in the box.", "example_kor": "고양이가 상자 안에 있다."},
    {"word": "for", "word_meaning": "~을 위해", "example_eng": "This gift is for you.", "example_kor": "이 선물은 너를 위한 것이다."},
    {"word": "on", "word_meaning": "~위에", "example_eng": "The book is on the desk.", "example_kor": "책이 책상 위에 있다."},
    {"word": "with", "word_meaning": "~와 함께", "example_eng": "I went to the park with my friend.", "example_kor": "나는 친구와 함께 공원에 갔다."},
    {"word": "at", "word_meaning": "~에", "example_eng": "Let's meet at the station.", "example_kor": "역에서 만나자."},
    {"word": "by", "word_meaning": "~옆에, ~에 의해", "example_eng": "The house is by the river.", "example_kor": "그 집은 강 옆에 있다."},
    {"word": "from", "word_meaning": "~로부터", "example_eng": "I got a letter from him.", "example_kor": "나는 그에게서 편지를 받았다."},
    {"word": "about", "word_meaning": "~에 대하여", "example_eng": "We talked about our future.", "example_kor": "우리는 우리의 미래에 대해 이야기했다."},
    # Conjunctions & Others (접속사 및 기타)
    {"word": "and", "word_meaning": "그리고", "example_eng": "I like bread and butter.", "example_kor": "나는 빵과 버터를 좋아한다."},
    {"word": "but", "word_meaning": "그러나", "example_eng": "I want to go, but I'm busy.", "example_kor": "가고 싶지만, 나는 바쁘다."},
    {"word": "or", "word_meaning": "또는", "example_eng": "Do you want coffee or tea?", "example_kor": "커피를 원하세요, 아니면 차를 원하세요?"},
    {"word": "so", "word_meaning": "그래서", "example_eng": "It was raining, so I took an umbrella.", "example_kor": "비가 와서, 나는 우산을 가져갔다."},
    {"word": "because", "word_meaning": "왜냐하면", "example_eng": "I was late because the traffic was bad.", "example_kor": "교통이 막혀서 나는 늦었다."},
    {"word": "what", "word_meaning": "무엇", "example_eng": "What is your name?", "example_kor": "당신의 이름은 무엇입니까?"},
    {"word": "who", "word_meaning": "누구", "example_eng": "Who is that person?", "example_kor": "저 사람은 누구입니까?"},
    {"word": "when", "word_meaning": "언제", "example_eng": "When is your birthday?", "example_kor": "너의 생일은 언제니?"},
    {"word": "where", "word_meaning": "어디", "example_eng": "Where are you from?", "example_kor": "어디에서 오셨어요?"},
    {"word": "why", "word_meaning": "왜", "example_eng": "Why are you crying?", "example_kor": "왜 울고 있니?"},
    {"word": "how", "word_meaning": "어떻게", "example_eng": "How are you?", "example_kor": "어떻게 지내세요?"}
]

# JSON 구조로 변환
voca_list = []
for w in basic_words:
    voca_list.append({
        "word": w["word"],
        "word_meaning": w["word_meaning"],
        "example": {
            "example_eng": w["example_eng"],
            "example_kor": w["example_kor"]
        }
    })

# 저장
with open("basic_200_voca.json", "w", encoding="utf-8") as f:
    json.dump(voca_list, f, ensure_ascii=False, indent=2)

print("basic_200_voca.json 파일 생성 완료! (200개 기초 단어)")